# Generated by Django 2.1.2 on 2018-10-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('cont', models.IntegerField(default=10)),
                ('name', models.CharField(max_length=30)),
                ('sno', models.IntegerField(default=4, primary_key=True, serialize=False)),
                ('expense', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('cont', models.IntegerField(default=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=20)),
                ('psw', models.CharField(max_length=20)),
            ],
        ),
    ]
