# Generated by Django 2.1.3 on 2018-12-15 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('expense', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='expense',
        ),
        migrations.RemoveField(
            model_name='register',
            name='uname',
        ),
        migrations.AlterField(
            model_name='register',
            name='cont',
            field=models.IntegerField(default=10, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Register'),
        ),
    ]
